/*
  SKANK-E WEBSITE CONTENT
  -----------------------
  This file is generated by the private local editor (editor.html).
  You can also edit it by hand if you prefer.

  Supported player types: soundcloud, mixcloud, youtube.
  Dub Lab sounds can use the built-in browser synth engines or a custom
  MP3/WAV/OGG file placed in assets/sounds/ (or an https:// audio URL).
*/

window.SKANK_E_DATA = {
  site: {
    heroTagline: "Reggae roots × funk breaks × hip-hop acapellas",
    heroSub: "Old-school cut-and-paste energy, built for big speakers.",
    aboutKicker: "HEAVYWEIGHT BLENDS SINCE WHENEVER THE PARTY STARTED",
    aboutTitle: "Sound-system\npressure with\nfunk in the trunk.",
    aboutParagraph1: "Skank-E is a mashup / bootleg DJ project blending reggae, dub, funk, hip-hop and breakbeat culture into bass-heavy edits made for parties rather than playlists.",
    aboutParagraph2: "The formula is simple: familiar voices, rude basslines, dusty drums, dub sirens and enough swing to keep the floor moving.",
    contactEyebrow: "BOOKINGS / DOWNLOADS / SOCIALS",
    contactTitle: "Turn it up.",
    contactNote: "Hit the links for music, downloads, socials and bookings.",
    footerText: "SKANK-E · MASH IT UP · PLAY IT LOUD"
  },

  releases: [
    {
      number: "001",
      title: "ADD YOUR FIRST BOOTLEG",
      subtitle: "Reggae vocal × funk break × hip-hop pressure",
      type: "soundcloud",
      url: "",
      downloadUrl: "",
      artworkClass: "artwork-a",
      label: "DUBPLATE"
    },
    {
      number: "002",
      title: "ADD YOUR SECOND MASHUP",
      subtitle: "Funk 45 × heavyweight bass × party edit",
      type: "mixcloud",
      url: "",
      downloadUrl: "",
      artworkClass: "artwork-b",
      label: "BOOTLEG"
    },
    {
      number: "003",
      title: "ADD YOUR VIDEO CUT",
      subtitle: "Old-school samples × dubwise video pressure",
      type: "youtube",
      url: "",
      downloadUrl: "",
      artworkClass: "artwork-c",
      label: "VIDEO"
    }
  ],

  players: [
    { type: "soundcloud", label: "SOUNDCLOUD", url: "" },
    { type: "mixcloud", label: "MIXCLOUD", url: "" },
    { type: "youtube", label: "YOUTUBE", url: "" }
  ],

  dubLab: {
    eyebrow: "LIVE FX / NO AUTOPLAY",
    title: "Make some\nnoise.",
    description: "Tap the controls for a little sound-system theatre. Use the built-in synth sounds or point any button at your own MP3, WAV or OGG file.",
    armedStatus: "FX armed. Click a button to fire.",
    rigLabel: "SKANK-E MOBILE SOUND",
    effects: [
      {
        label: "SIREN",
        sublabel: "WOOOOP",
        source: "generated",
        engine: "siren",
        audioUrl: "",
        params: {
          waveform: "sawtooth",
          startFrequency: 440,
          peakFrequency: 880,
          endFrequency: 520,
          peakTime: 0.45,
          duration: 1.05,
          filterFrequency: 2200,
          volume: 0.12
        }
      },
      {
        label: "ECHO",
        sublabel: "CHOP",
        source: "generated",
        engine: "echo",
        audioUrl: "",
        params: {
          burstDuration: 0.09,
          filterFrequency: 850,
          delayTime: 0.22,
          feedback: 0.48,
          volume: 0.18
        }
      },
      {
        label: "SPRING",
        sublabel: "BOING",
        source: "generated",
        engine: "spring",
        audioUrl: "",
        params: {
          baseFrequency: 130,
          frequencySpread: 57,
          decay: 0.24,
          taps: 4,
          volume: 0.05
        }
      }
    ]
  },

  links: [
    { label: "SoundCloud", url: "" },
    { label: "Mixcloud", url: "" },
    { label: "YouTube", url: "" },
    { label: "Instagram", url: "" },
    { label: "Booking email", url: "" }
  ]
};
